// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object FlutterNativeApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class NativePageParams (
  val fromFlutter: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativePageParams {
      val fromFlutter = pigeonVar_list[0] as Boolean
      return NativePageParams(fromFlutter)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      fromFlutter,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativePageParams
    return FlutterNativeApiPigeonUtils.deepEquals(this.fromFlutter, other.fromFlutter)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + FlutterNativeApiPigeonUtils.deepHash(this.fromFlutter)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TupleBool (
  val code: Long,
  val msg: String,
  val data: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TupleBool {
      val code = pigeonVar_list[0] as Long
      val msg = pigeonVar_list[1] as String
      val data = pigeonVar_list[2] as Boolean
      return TupleBool(code, msg, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      msg,
      data,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TupleBool
    return FlutterNativeApiPigeonUtils.deepEquals(this.code, other.code) && FlutterNativeApiPigeonUtils.deepEquals(this.msg, other.msg) && FlutterNativeApiPigeonUtils.deepEquals(this.data, other.data)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + FlutterNativeApiPigeonUtils.deepHash(this.code)
    result = 31 * result + FlutterNativeApiPigeonUtils.deepHash(this.msg)
    result = 31 * result + FlutterNativeApiPigeonUtils.deepHash(this.data)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TupleStr (
  val code: Long,
  val msg: String,
  val data: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TupleStr {
      val code = pigeonVar_list[0] as Long
      val msg = pigeonVar_list[1] as String
      val data = pigeonVar_list[2] as String?
      return TupleStr(code, msg, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      msg,
      data,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TupleStr
    return FlutterNativeApiPigeonUtils.deepEquals(this.code, other.code) && FlutterNativeApiPigeonUtils.deepEquals(this.msg, other.msg) && FlutterNativeApiPigeonUtils.deepEquals(this.data, other.data)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + FlutterNativeApiPigeonUtils.deepHash(this.code)
    result = 31 * result + FlutterNativeApiPigeonUtils.deepHash(this.msg)
    result = 31 * result + FlutterNativeApiPigeonUtils.deepHash(this.data)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class FlutterPageParams (
  val fromNative: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FlutterPageParams {
      val fromNative = pigeonVar_list[0] as Boolean
      return FlutterPageParams(fromNative)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      fromNative,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as FlutterPageParams
    return FlutterNativeApiPigeonUtils.deepEquals(this.fromNative, other.fromNative)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + FlutterNativeApiPigeonUtils.deepHash(this.fromNative)
    return result
  }
}
private open class FlutterNativeApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativePageParams.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TupleBool.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TupleStr.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FlutterPageParams.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativePageParams -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is TupleBool -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is TupleStr -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is FlutterPageParams -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NativeApis {
  /** 跳转原生页面 */
  fun goNativePage(router: String, params: NativePageParams?): TupleBool
  /** 是否有读写权限 */
  fun hasReadWritePermission(): TupleBool
  /** 请求读写权限,需要异步 */
  fun grantReadWritePermission(callback: (Result<TupleBool>) -> Unit)
  fun getExternalStorageRootPath(): TupleStr
  fun getDefaultOutputDirPath(): TupleStr
  fun copyCacheAudioVideoFile(sufPath: String, callback: (Result<TupleBool>) -> Unit)
  fun copyCacheStructureFile(callback: (Result<TupleBool>) -> Unit)
  fun notifyExportComplete(callback: (Result<TupleBool>) -> Unit)

  companion object {
    /** The codec used by NativeApis. */
    val codec: MessageCodec<Any?> by lazy {
      FlutterNativeApiPigeonCodec()
    }
    /** Sets up an instance of `NativeApis` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeApis?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hlbmerge.NativeApis.goNativePage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val routerArg = args[0] as String
            val paramsArg = args[1] as NativePageParams?
            val wrapped: List<Any?> = try {
              listOf(api.goNativePage(routerArg, paramsArg))
            } catch (exception: Throwable) {
              FlutterNativeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hlbmerge.NativeApis.hasReadWritePermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.hasReadWritePermission())
            } catch (exception: Throwable) {
              FlutterNativeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hlbmerge.NativeApis.grantReadWritePermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.grantReadWritePermission{ result: Result<TupleBool> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(FlutterNativeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(FlutterNativeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hlbmerge.NativeApis.getExternalStorageRootPath$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getExternalStorageRootPath())
            } catch (exception: Throwable) {
              FlutterNativeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hlbmerge.NativeApis.getDefaultOutputDirPath$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getDefaultOutputDirPath())
            } catch (exception: Throwable) {
              FlutterNativeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hlbmerge.NativeApis.copyCacheAudioVideoFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sufPathArg = args[0] as String
            api.copyCacheAudioVideoFile(sufPathArg) { result: Result<TupleBool> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(FlutterNativeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(FlutterNativeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hlbmerge.NativeApis.copyCacheStructureFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.copyCacheStructureFile{ result: Result<TupleBool> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(FlutterNativeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(FlutterNativeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hlbmerge.NativeApis.notifyExportComplete$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.notifyExportComplete{ result: Result<TupleBool> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(FlutterNativeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(FlutterNativeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class FlutterApis(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by FlutterApis. */
    val codec: MessageCodec<Any?> by lazy {
      FlutterNativeApiPigeonCodec()
    }
  }
  fun backFlutterPageFromNativePage(paramsArg: FlutterPageParams?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.hlbmerge.FlutterApis.backFlutterPageFromNativePage$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(paramsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(FlutterNativeApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
